### ISSUE TITLE
Change common dependency

### ISSUE THREAD

**Issue by aryann** [googleapis/google-cloud-cpp-bigquery#12]
This is what we should be depending on, not https://github.com/googleapis/google-cloud-cpp/archive/v0.13.0.tar.gz:

https://github.com/googleapis/google-cloud-cpp-common/archive/v0.13.0.tar.gz

https://github.com/googleapis/google-cloud-cpp-common/releases

**Comment by devjgm** [comment]
This issue is stale. Closing.
