### ISSUE TITLE
Investigate build failures with Bazel 1.0.0

### ISSUE THREAD

**Issue by aryann** [googleapis/google-cloud-cpp-bigquery#25]
The best way to reproduce this is by using the ci/ scripts:

```bash
cd ci
sudo docker build .   --file kokoro/docker/Dockerfile.ubuntu   --tag gcpp-ci-ubuntu-18.04:latest
kokoro/docker/build.sh asan
```

Error is:

`
ERROR: /h/.cache/bazel/_bazel_aryan/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/BUILD.bazel:24:1: in srcs attribute of _generate_cc rule @com_google_googleapis//:_grpc_bigquerystorage_proto_grpc_codegen: '@com_google_googleapis//google/cloud/bigquery/storage/v1beta1:bigquerystorage_proto' does not have mandatory providers: 'proto'. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /h/.cache/bazel/_bazel_aryan/a7ecd8237744645c5d189c197108d6d2/external/com_google_googleapis/BUILD.bazel:24:1
`

**Comment by coryan** [comment]
I will take a stab at this.
